spring:
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/notification_managment?authSource=admin
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9092}
  application:
    name: notification-service
server:
  port: '9010'
botToken: 7336930762:AAEoUye02s_DwuiOjZPWA9KeriSe5GFjrvc
