version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=anton
      - POSTGRES_USER=anton
      - POSTGRES_DB=online-shop
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "9003:9003"
    depends_on:
      - postgres

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "9002:9002"
    depends_on:
      - postgres

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    depends_on:
      - postgres
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
    depends_on:
      - kafka


volumes:
  postgres_data:
