server:
  port: 9001

springdoc:
  swagger-ui:
    path: /swagger/swagger-ui.html

spring:
  application:
    name: user-service
  liquibase:
    change-log: classpath:db/changelog.xml
    enabled: true
    user: anton
    password: anton
    default-schema:  user_management
    liquibase-schema: user_management_migrations
  datasource:
    username: anton
    password: anton
    url: ${URL:jdbc:postgresql://postgres:5432/online-shop}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: user_management
        dialect: org.hibernate.dialect.PostgreSQLDialect

application:
  order-service:
    url: ${PRODUCT_SERVICE_URL:http://localhost:9003}
    path: ${PRODUCT_SERVICE_PATH:/api/orders/users}
