server:
  port: ${PORT:9003}

springdoc:
  swagger-ui:
    path: /swagger/swagger-ui.html

spring:
  #security:
  #  oauth2:
  #    resourceserver:
  #      jwt:
  #        jwk-set-uri: ${KEYCLOAK_JWK_URL:http://localhost:8081/realms/demo/protocol/openid-connect/certs}
  application:
    name: order-service
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: online-shop
  liquibase:
    change-log: classpath:db/changelog.xml
    enabled: true
    user: ${DATABASE_USERNAME:anton}
    password: ${DATABASE_PASSWORD:anton}
    default-schema: ${DEFAULT_SCHEMA:order_management}
    liquibase-schema: ${LIQUIBASE_SCHEMA:order_management_migrations}
  datasource:
    username: ${DATABASE_USERNAME:anton}
    password: ${DATABASE_PASSWORD:anton}
    url: jdbc:postgresql://localhost:5432/online-shop
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: ${DEFAULT_SCHEMA:order_management}
        dialect: org.hibernate.dialect.PostgreSQLDialect

application:
  product-service:
    url: ${PRODUCT_SERVICE_URL:http://localhost:9002}
    path: ${PRODUCT_SERVICE_PATH:/products}