server:
  port: 9003

springdoc:
  swagger-ui:
    path: /swagger/swagger-ui.html

spring:
  application:
    name: order-service
  liquibase:
    change-log: classpath:db/changelog.xml
    enabled: true
    user: anton
    password: anton
    default-schema:  order_management
    liquibase-schema: order_management_migrations
  datasource:
    username: anton
    password: anton
    #url: jdbc:postgresql://localhost:5432/online-shop
    url: jdbc:postgresql://localhost:5432/online-shop
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: order_management
        dialect: org.hibernate.dialect.PostgreSQLDialect

application:
  product-service:
    url: ${PRODUCT_SERVICE_URL:http://localhost:9002}
    path: ${PRODUCT_SERVICE_PATH:/products}