server:
  port: 9002

springdoc:
  swagger-ui:
    path: /swagger/swagger-ui.html

spring:
  application:
    name: user-service
  liquibase:
    change-log: classpath:db/changelog.xml
    enabled: true
    default-schema:  product_management
    liquibase-schema: product_management_migrations
  datasource:
    username: anton
    password: anton
    url: jdbc:postgresql://localhost:5432/online-shop
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: product_management
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      schema-locations: classpath:db/schema.sql