name: Build all micro-services

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [gateway-service, notification-service, order-service, product-service, user-service]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build ${{ matrix.service }}
      run: |
        cd ${{ matrix.service }}
        chmod +x ./gradlew 
        ./gradlew build -x test

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.service }}-artifacts
        path: ${{ matrix.service }}/build/libs/*.jar

